<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Dtos\RolDto\**" />
    <Compile Remove="Services\LibrosServices\**" />
    <Compile Remove="Services\NotificacionesServices\**" />
    <Compile Remove="Services\Prestamos_y_PenalizacionServices\**" />
    <EmbeddedResource Remove="Dtos\RolDto\**" />
    <EmbeddedResource Remove="Services\LibrosServices\**" />
    <EmbeddedResource Remove="Services\NotificacionesServices\**" />
    <EmbeddedResource Remove="Services\Prestamos_y_PenalizacionServices\**" />
    <None Remove="Dtos\RolDto\**" />
    <None Remove="Services\LibrosServices\**" />
    <None Remove="Services\NotificacionesServices\**" />
    <None Remove="Services\Prestamos_y_PenalizacionServices\**" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Contracts\Service\ILibroServices\" />
    <Folder Include="Contracts\Service\INotificacionesServices\" />
    <Folder Include="Contracts\Service\IPrestamos_y_ PenalizacionServices\" />
    <Folder Include="validators\FluentValidators\Reorte_Y_Estadistica\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation" Version="12.0.0" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="12.0.0" />
    <PackageReference Include="Microsoft.AspNet.WebApi.Client" Version="6.0.0" />
    <PackageReference Include="Microsoft.Extensions.ApiDescription.Server" Version="8.0.1">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="8.0.0" />
    <PackageReference Include="Microsoft.Extensions.Logging" Version="8.0.1" />
    <PackageReference Include="Microsoft.SqlServer.Server" Version="1.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SGB.Domain\SGB.Domain.csproj" />
  </ItemGroup>

</Project>
