<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Dtos\RolDto\**" />
    <EmbeddedResource Remove="Dtos\RolDto\**" />
    <None Remove="Dtos\RolDto\**" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Contracts\Interfaces\Service\ILibroServices\" />
    <Folder Include="Contracts\Interfaces\Service\IReporte_EstadisticaServices\" />
    <Folder Include="Contracts\Interfaces\Service\IUsuarioServices\" />
    <Folder Include="Contracts\Interfaces\Service\INotificacionesServices\" />
    <Folder Include="Services\LibrosServices\" />
    <Folder Include="Services\UsuarioServices\" />
    <Folder Include="Services\Reporte_EstaditicaServices\" />
    <Folder Include="Services\NotificacionesServices\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation" Version="12.0.0" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="12.0.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="8.0.0" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="8.0.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SGB.Domain\SGB.Domain.csproj" />
  </ItemGroup>

</Project>
