<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Models\ConfiguracionModels\**" />
    <Compile Remove="Models\models admin Sistema\**" />
    <Compile Remove="Models\models Libros\**" />
    <Compile Remove="Models\models Notificaciones\**" />
    <Compile Remove="Models\Models Reporte Estadistica\**" />
    <Compile Remove="Models\models Usuario\**" />
    <EmbeddedResource Remove="Models\ConfiguracionModels\**" />
    <EmbeddedResource Remove="Models\models admin Sistema\**" />
    <EmbeddedResource Remove="Models\models Libros\**" />
    <EmbeddedResource Remove="Models\models Notificaciones\**" />
    <EmbeddedResource Remove="Models\Models Reporte Estadistica\**" />
    <EmbeddedResource Remove="Models\models Usuario\**" />
    <None Remove="Models\ConfiguracionModels\**" />
    <None Remove="Models\models admin Sistema\**" />
    <None Remove="Models\models Libros\**" />
    <None Remove="Models\models Notificaciones\**" />
    <None Remove="Models\Models Reporte Estadistica\**" />
    <None Remove="Models\models Usuario\**" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Models\" />
  </ItemGroup>

</Project>
